name: CI tests

on: ['push', 'pull_request']

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7.15, 3.8.16, 3.9.16, 3.10.10, 3.11.2]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=eventdispatcher --cov-report xml --cov-report term-missing

    # The following step will only be run for python 3.11.2
    - name: Upload coverage report to Codecov
      if: matrix.python-version == '3.11.2'
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittest
        name: eventdispatcher3
        fail_ci_if_error: true
